version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xxx
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile.prod
    volumes:
      - static:/app/static
      - media:/app/media
    environment:
      SECRET_KEY: xxx
      DEBUG: 0
      ORIGIN: http://localhost:8000
      DB_HOST: db
      DB_NAME: xxx
      DB_USER: xxx
      DB_PASS: xxx
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.prod
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:80
    volumes:
      - static:/usr/share/nginx/static
      - media:/usr/share/nginx/media
    depends_on:
      - backend
      - frontend

volumes:
  db:
  media:
  static: