version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cosmac
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
  backend:
    build: ./backend
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      SECRET_KEY: SUPER TAJNY SEKRET
      DEBUG: 1
      DB_HOST: db
      DB_NAME: cosmac
      DB_USER: root
      DB_PASS: secret
    depends_on:
      - db
  frontend:
    build: ./frontend
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  db:
