version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xxx
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - /app/static
      - /app/media
    environment:
      SECRET_KEY: xxx
      DEBUG: 1
      ORIGIN: http://localhost:3000
      DB_HOST: db
      DB_NAME: xxx
      DB_USER: xxx
      DB_PASS: xxx
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - 4000:80
    volumes:
      - ./backend/static:/usr/share/nginx/static
      - ./backend/media:/usr/share/nginx/media
    depends_on:
      - backend
      - frontend

volumes:
  db:
  static:
  media:
