version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cosmac
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      SECRET_KEY: SUPER TAJNY SEKRET
      DEBUG: 1
      ORIGIN: http://localhost:8000
      DB_HOST: backend
      DB_NAME: cosmac
      DB_USER: root
      DB_PASS: secret
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports: 
      - 80:3000
      - 443:3000
    depends_on:
      - backend

volumes:
  db:
