version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cosmac
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile.prod
    volumes:
      - media:/app/media
    environment:
      SECRET_KEY: SUPER TAJNY SEKRET
      DEBUG: 1
      DB_HOST: db
      DB_NAME: cosmac
      DB_USER: root
      DB_PASS: secret
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.prod
    depends_on:
      - backend
  nginx:
    build: 
      context: ./nginx
      dockerfile: dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  db:
  media:
